### ISSUE TITLE
Upcoming API change request

### ISSUE THREAD

**Issue by nuzzles** [simbleau/chat-translator#14]
A recent API change in 1.8.7-SNAPSHOT (https://github.com/runelite/runelite/commit/409d0dda7661468d0cc3c664894421bc7e17f1b2) is incompatible with this plugin. You must update your plugin and PR it to the plugin-hub/1.8.7 branch prior to Dec 15 to avoid any disruption

**Comment by jnblas** [comment]
any update on this?

**Comment by nuzzles** [comment]
Unfortunately this is not currently my priority. Totally accepting PRs to those willing, but I don't play RS right now so... :/ na.

This would be on hold until I have motivation.
